name: TestPROGPOE2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List contents
        run: ls

      - name: Compile classes
        working-directory: ./src
        run: javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" ./st10341562/St10341562.java "../test/st10341562/St10341562Test.java"

      - name: List contents of src directory after compile
        working-directory: ./src/st10341562
        run: ls

      - name: Copy compiled classes to testresources directory
        working-directory: ./src/st10341562
        run: cp -t "../../test/st10341562" St10341562.class

      - name: Copy compiled test classes to testresources directory
        working-directory: ./test/st10341562
        run: cp -t "../../testresources/" St10341562Test.class

      - name: List contents of test package
        working-directory: ./test/st10341562
        run: ls

      - name: Run St10341562Test class and generate report
        working-directory: ./test
        run: |
          ls
          java -jar "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class st10341562.St10341562Test
